### ISSUE TITLE
bleach EOL

### ISSUE THREAD

**Issue by onno-timmerman** [withlogicco/django-prose#80] opened 2024-02-09 12:42 UTC
https://github.com/mozilla/bleach/issues/698

Bleach will die soon

**Comment by parisk** [comment] 2024-02-09 14:57
Duplicate of #36.

Thanks for the comment @onno-timmerman! We have moved the conversation to https://github.com/withlogicco/django-prose/discussions/38, to find a potential solution for the future.

**Closed by parisk** 2024-02-09 14:57 UTC
